<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('APP URREA')->setSeparator(' | ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        				->prependStylesheet($this->basePath() . '/assets/css/style.css')
		                ->prependStylesheet($this->basePath() . '/assets/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css')
		?>
		<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
		
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
        ; ?>
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
    	<header>
			<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	            <div class="container">
	                <div class="navbar-header">
	                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
	                    	<img src="<?php echo $this->basePath('/assets/img/logo.png') ?>" alt="nuup"/>
	                    </a>
	                </div>
	                <ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-inbox fa-lg"></i>
								3 new messages <span class="caret"></span>
							</a>
							<ul class="dropdown-menu" role="menu">
								<li>
									<a href="#"><i class="fa fa-info-circle"></i> mensaje uno</a>
								</li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<span class="glyphicon glyphicon-user"></span> 
								<?= $this->zfcUserIdentity()->getDisplayname(); ?> <span class="caret"></span>
							</a>
							<ul class="dropdown-menu" role="menu">
								<li>
									<a href="#"><i class="fa fa-info-circle"></i> Información de usuario</a>
								</li>
								<li>
									<a href="#">
										<i class="fa fa-lock"></i> Cambiar contraseña
									</a>
								</li>
								<li class="divider"></li>
								<li>
									<a href="#">
										<i class="fa fa-life-ring"></i> Ayuda
									</a>
								</li>
								<li>
									<a href="#">
										<i class="fa fa-bug"></i> Reportar un problema
									</a>
								</li>
								<li class="divider"></li>
								<li>
									<a href="#">
										<i class="fa fa-power-off"></i> Logout
									</a>
								</li>
							</ul>
						</li>
					</ul>
	            </div>
	        </nav>
       </header>
        <div class="clearfix"></div>
       	<div id="content" class="container">
        	<!-- container -->
			<div class="sidebar">
				<ul class="nav nav-pills nav-stacked">
					<li>
						<a href="#" title="Dashboard" class="dashboard link_tooltip" data-toggle="tooltip" data-placement="right" >
							<i class="fa fa-tasks fa-lg"></i>
						</a>
						<a href="#" title="Users" class="products link_tooltip" data-toggle="tooltip" data-placement="right" >
							<i class="fa fa-users fa-lg"></i>
						</a>
						<a href="#" title="Categorías" class="categories link_tooltip" data-toggle="tooltip" data-placement="right" >
							<i class="fa fa-cubes fa-lg"></i>
						</a>
						<a href="#" title="Colecciones" class="collections link_tooltip" data-toggle="tooltip" data-placement="right" >
							<i class="fa fa-tags fa-lg"></i>
						</a>
						<a href="#" title="Escenarios" title="Escenarios" class="stages link_tooltip" data-toggle="tooltip" data-placement="right" >
							<i class="fa fa-calendar fa-lg"></i>
						</a>
						<a href="#" title="Escenarios" title="Escenarios" class="crud link_tooltip" data-toggle="tooltip" data-placement="right" >
							<i class="fa fa-line-chart fa-lg"></i>
						</a>
					</li>
				</ul>
			</div>
			<div class="right_panel"><?php echo $this->content; ?></div>
			<!-- /container -->
		</div>
        <footer>
            <p class="container">&copy; 2014 <?php echo $this->translate('All rights reserved.') ?> | <a href="http://develephant.mx">develephant</a></p>
        </footer>
        <?php echo $this->headScript()  
                ->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery-1.11.0.js') ?>
    </body>
</html>
